### ISSUE TITLE
React-Native-Web support

### ISSUE THREAD

**Issue by RangerMauve** [kadirahq/react-native-storybook#118]
It would be cool if this project supported [react-native-web](https://github.com/necolas/react-native-web). Essentially, having the same interface as the Android or iOS version, but spawning the code inside a new browser window.

**Comment by arunoda** [comment]
I wonder what you mean by this. React Native Web, actually use storybook as it's [documentation](http://necolas.github.io/react-native-web/storybook/?selectedKind=APIs&selectedStory=Clipboard&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel).

You could simply use our react-storybook for that.

**Comment by arunoda** [comment]
Basically, you need to create an alias for RNW with our [custom webpack config](https://getstorybook.io/docs/react-storybook/configurations/custom-webpack-config).

**Comment by RangerMauve** [comment]
Is it possible, then, to use both the React Native storybook and the regular storybook together in the same project?

**Comment by holmesal** [comment]
@RangerMauve right, so that you could have a react-native-web component rendered in the area on the left, and then optionally a native component rendered in the simulator.

This would actually be really useful for me. I've been teaching designers to Storybook, so that they can update styles and see the changes on the component-level. Getting them all set up with xcode and etc always seems to turn into a dumpster fire, and they don't *really* need a true native preview - the (tiny) differences btwn react-native-web and react-native would be acceptable for us.

I'm not sure if this is possible with the way that react-native-storybook is built currently. @arunoda can correct me, but I think that the story files are parsed on the native side, and then sent via websocket to the storybook ui (running in chrome or w/e)? If so, it doesn't seem like this would be possible, at least until #6 is resolved.
