### ISSUE TITLE
ios device "websocket: connection error"

### ISSUE THREAD

**Issue by rohit-ravikoti** [kadirahq/react-native-storybook#122]
Hi,
I'm not sure if this functionality is supported, but when I try to run the app on a real ios device, I get the following error:
```
2017-02-08 13:18:52.831 [error][tid:com.facebook.react.JavaScript] 'websocket: connection error', 'The operation couldn’t be completed. Connection refused'
2017-02-08 13:18:52.865 [error][tid:com.facebook.react.JavaScript] 'websocket: connection closed', undefined, undefined
```

**Comment by admmasters** [comment]
E

**Comment by chrismcleod** [comment]
@rohit-ravikoti 
This is because react native uses "localhost" as the default port for the packager.  This doesn't work for react native storybook.  I'm guessing because it expects that the storybook server is running on the same host as the packager.  However, the storybook host is not on the ios device, it is on your development computer.  So, replace all the localhost references with your computer's internal IP address.  That can be found by going to **System Settings > Network**.

If your internal ip address is 10.0.1.16:

open your react native project with XCode and go to: 
_ProjectName_ > Libraries > RCTWebSocket.xcodeproj > RCTWebSocketExecutor.m

got to the method - (void)setUp and (toward the top) change 
`host = @"localhost"` to `host = @"10.0.1.16"`.

![image](https://cloud.githubusercontent.com/assets/1134683/23582355/f079e61e-00ed-11e7-9aa5-6746efb076d0.png)

create storybook like this:
`const StorybookUI = getStorybookUI({ port: 7007, host: "10.0.1.16" });`

start it like this:
`npm run storybook -- -h 10.0.1.16`

After making all the changes, I'd probably close all simulators, stop all packagers and close the app on the phone.

**Comment by ndelangen** [comment]
Please open an issue over at the new repo if you're still experiencing this issue, thanks!
